name: Multi Job Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  changed-files:
    name: "Get changed files using Github's REST API"
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  view-changed-files:
    name: View all changed files
    runs-on: ubuntu-latest
    needs: [changed-files]
    steps:
      - name: List all changed files
        run: |
          echo '${{ needs.changed-files.outputs.all_changed_files }}'
